const menu = [
  {
    id: 1,
    title: 'Dosa and Idly',
    category: 'breakfast',
    price: 10.99,
    img: './images/item-1 breakfast.jpg',
    desc: `Famous Idly and Dosa Breakfast you can eat now  Idly is Good for health `,
  },
  {
    id: 2,
    title: 'Upma',
    category: 'breakfast',
    price: 13.99,
    img: './images/item-2 breakfast.jpg',
    desc: `Upma is a savory South Indian tiffin made from semolina (rava) cooked with spices, vegetables, and garnished with fresh herbs`,
  },
  {
    id: 3,
    title: 'Vada',
    category: 'breakfast',
    price: 6.99,
    img: './images/item-3 breakfast.jpg',
    desc: `Vada is a popular South Indian deep-fried snack made from spiced lentil or potato batter, crispy on the outside and soft on the inside.`,
  },
  {
    id: 4,
    title: 'breakfast',
    category: 'breakfast',
    price: 20.99,
    img: './images/item-4 breakfast.jpg',
    desc: `Bread is a baked staple made from flour, water, and yeast, enjoyed in various forms and flavors worldwide.`,
  },
  {
    id: 5,
    title: 'egg attack',
    category: 'breakfast',
    price: 22.99,
    img: './images/item-5 breakfast.jpg',
    desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
  },
  {
    id: 6,
    title: 'oreo dream',
    category: 'breakfast',
    price: 18.99,
    img: './images/item-6 breakfast.jpg',
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
  },
  {
    id: 7,
    title: 'bacon overflow',
    category: 'desserts',
    price: 8.99,
    img: './images/item-7 dessert.jpg',
    desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
  },
  {
    id: 8,
    title: 'american classic',
    category: 'desserts',
    price: 12.99,
    img: './images/item-9 dessert.jpg',
    desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
  },
  {
    id: 9,
    title: 'quarantine buddy',
    category: 'desserts',
    price: 16.99,
    img: './images/item-10 dessert.jpg',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
  {
    id: 10,
    title: 'quarantine buddy',
    category: 'lunch',
    price: 16.99,
    img: './images/item-11 lunch.jpg',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
  {
    id: 11,
    title: 'quarantine buddy',
    category: 'lunch',
    price: 16.99,
    img: './images/item-12 lunch.jpg',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
  {
    id: 12,
    title: 'quarantine buddy',
    category: 'lunch',
    price: 16.99,
    img: './images/item-13 lunch.jpg',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
  {
    id: 13,
    title: 'quarantine buddy',
    category: 'lunch',
    price: 16.99,
    img: './images/item-14 lunch.jpg',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
  {
    id: 14,
    title: 'quarantine buddy',
    category: 'Drinks',
    price: 16.99,
    img: './images/item-15 drinks.jpg',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
  {
    id: 15,
    title: 'quarantine buddy',
    category: 'Drinks',
    price: 16.99,
    img: './images/item-16 drinks.jpg',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
  {
    id: 16,
    title: 'quarantine buddy',
    category: 'Drinks',
    price: 16.99,
    img: './images/item-17 drinks.jpg',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
  {
    id: 17,
    title: 'quarantine buddy',
    category: 'Drinks',
    price: 16.99,
    img: './images/item-18 drinks.jpg',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
  {
    id: 18,
    title: 'quarantine buddy',
    category: 'Drinks',
    price: 16.99,
    img: './images/item-19 drinks.jpg',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
  
];
export default menu;